#!/usr/bin/env bash
#Script that install Nginx Web Server
sudo apt-get -y update
sudo apt-get -y install nginx
sudo ufw app list
sudo ufw allow 'Nginx HTTP'
echo 'Holberton School' > /var/www/html/index.html
service nginx start
