#!/usr/bin/env bash
#Script that install Nginx Web Server
#./0-transfer_file 1-install_nginx_web_server 35.185.28.243 ubuntu ~/.ssh/id_rsa
sudo apt-get -y update
sudo apt-get -y install nginx
echo 'Holberton School' > /var/www/html/index.html
sudo sed -i '46i rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default
sudo service nginx restart
