#!/usr/bin/env bash
# Script that configures the nginx server listening on port 80
ln -sf /etc/nginx/sities-available/default /etc/nginx/sites-enabled/default
service nginx start
kill "$(pgrep 'nginx' | head -1)"
